[bot]
discord_token = "MTA1MzgxODA0NTA3MzczOTgxNw.GFBPjJ.0SV-D_hQkuXjlEXqMb42POUKcB6U96Lcnmszng"
client_id = ""

[api]
use_https = true
host_port = 3000

[core]
debug_mode = true
blacklist_picture_url = "https://url-to-link"
guild_logs_channel_id = "1139545238533312662"